services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile.development
    env_file: .env
    volumes:
      - ./apps/client:/app/apps/client
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    networks:
      - app_network
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile.development
    env_file: .env
    volumes:
      - ./apps/server:/app/apps/server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - app_network
    depends_on:
      - database

  database:
    image: postgres:15.2
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  database:

networks:
  app_network:
    driver: bridge
