- hosts: all
  tasks:
    - name: Clear old images
      community.docker.docker_prune:
        containers: true
        images: true

    - name: Start docker container
      community.docker.docker_container:
        name: app
        image: "chernenkoivan/plata:{{ VERSION }}"
        restart_policy: always
        state: started
        ports:
          - 80:80
        env: HOST="0.0.0.0"
          PORT="80"
          DB_PASSWORD="{{ DB_PASSWORD }}"
          DB_USERNAME="{{ DB_USERNAME }}"
          DB_HOST="{{ DB_HOST }}"
          DB_PORT="{{ DB_PORT }}"
          DB_NAME="{{ DB_NAME }}"
