/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as AuthLayoutRouteImport } from './routes/_auth-layout/route'
import { Route as AuthLayoutIndexImport } from './routes/_auth-layout/index'
import { Route as AuthLayoutAccountsCreateImport } from './routes/_auth-layout/accounts/create'
import { Route as AuthLayoutAccountsIdImport } from './routes/_auth-layout/accounts/$id'
import { Route as AuthLayoutAccountsIdTransactionsCreateImport } from './routes/_auth-layout/accounts/$id_.transactions.create'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRouteRoute = AuthLayoutRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutIndexRoute = AuthLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)

const AuthLayoutAccountsCreateRoute = AuthLayoutAccountsCreateImport.update({
  id: '/accounts/create',
  path: '/accounts/create',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)

const AuthLayoutAccountsIdRoute = AuthLayoutAccountsIdImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)

const AuthLayoutAccountsIdTransactionsCreateRoute =
  AuthLayoutAccountsIdTransactionsCreateImport.update({
    id: '/accounts/$id_/transactions/create',
    path: '/accounts/$id/transactions/create',
    getParentRoute: () => AuthLayoutRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout/': {
      id: '/_auth-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutIndexImport
      parentRoute: typeof AuthLayoutRouteImport
    }
    '/_auth-layout/accounts/$id': {
      id: '/_auth-layout/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AuthLayoutAccountsIdImport
      parentRoute: typeof AuthLayoutRouteImport
    }
    '/_auth-layout/accounts/create': {
      id: '/_auth-layout/accounts/create'
      path: '/accounts/create'
      fullPath: '/accounts/create'
      preLoaderRoute: typeof AuthLayoutAccountsCreateImport
      parentRoute: typeof AuthLayoutRouteImport
    }
    '/_auth-layout/accounts/$id_/transactions/create': {
      id: '/_auth-layout/accounts/$id_/transactions/create'
      path: '/accounts/$id/transactions/create'
      fullPath: '/accounts/$id/transactions/create'
      preLoaderRoute: typeof AuthLayoutAccountsIdTransactionsCreateImport
      parentRoute: typeof AuthLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteRouteChildren {
  AuthLayoutIndexRoute: typeof AuthLayoutIndexRoute
  AuthLayoutAccountsIdRoute: typeof AuthLayoutAccountsIdRoute
  AuthLayoutAccountsCreateRoute: typeof AuthLayoutAccountsCreateRoute
  AuthLayoutAccountsIdTransactionsCreateRoute: typeof AuthLayoutAccountsIdTransactionsCreateRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutIndexRoute: AuthLayoutIndexRoute,
  AuthLayoutAccountsIdRoute: AuthLayoutAccountsIdRoute,
  AuthLayoutAccountsCreateRoute: AuthLayoutAccountsCreateRoute,
  AuthLayoutAccountsIdTransactionsCreateRoute:
    AuthLayoutAccountsIdTransactionsCreateRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthLayoutRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/': typeof AuthLayoutIndexRoute
  '/accounts/$id': typeof AuthLayoutAccountsIdRoute
  '/accounts/create': typeof AuthLayoutAccountsCreateRoute
  '/accounts/$id/transactions/create': typeof AuthLayoutAccountsIdTransactionsCreateRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthLayoutIndexRoute
  '/accounts/$id': typeof AuthLayoutAccountsIdRoute
  '/accounts/create': typeof AuthLayoutAccountsCreateRoute
  '/accounts/$id/transactions/create': typeof AuthLayoutAccountsIdTransactionsCreateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth-layout': typeof AuthLayoutRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_auth-layout/': typeof AuthLayoutIndexRoute
  '/_auth-layout/accounts/$id': typeof AuthLayoutAccountsIdRoute
  '/_auth-layout/accounts/create': typeof AuthLayoutAccountsCreateRoute
  '/_auth-layout/accounts/$id_/transactions/create': typeof AuthLayoutAccountsIdTransactionsCreateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/'
    | '/accounts/$id'
    | '/accounts/create'
    | '/accounts/$id/transactions/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/accounts/$id'
    | '/accounts/create'
    | '/accounts/$id/transactions/create'
  id:
    | '__root__'
    | '/_auth-layout'
    | '/auth'
    | '/_auth-layout/'
    | '/_auth-layout/accounts/$id'
    | '/_auth-layout/accounts/create'
    | '/_auth-layout/accounts/$id_/transactions/create'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth-layout",
        "/auth"
      ]
    },
    "/_auth-layout": {
      "filePath": "_auth-layout/route.tsx",
      "children": [
        "/_auth-layout/",
        "/_auth-layout/accounts/$id",
        "/_auth-layout/accounts/create",
        "/_auth-layout/accounts/$id_/transactions/create"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/_auth-layout/": {
      "filePath": "_auth-layout/index.tsx",
      "parent": "/_auth-layout"
    },
    "/_auth-layout/accounts/$id": {
      "filePath": "_auth-layout/accounts/$id.tsx",
      "parent": "/_auth-layout"
    },
    "/_auth-layout/accounts/create": {
      "filePath": "_auth-layout/accounts/create.tsx",
      "parent": "/_auth-layout"
    },
    "/_auth-layout/accounts/$id_/transactions/create": {
      "filePath": "_auth-layout/accounts/$id_.transactions.create.tsx",
      "parent": "/_auth-layout"
    }
  }
}
ROUTE_MANIFEST_END */
