name: deploy
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository
        uses: actions/checkout@v2

      - name: Get commit hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: "chernenkoivan/plata:${{ steps.commit.outputs.short }}"

      - name: Prepare servers
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: prepare-servers.yml
          inventory: |
            [do_servers]
            root@161.35.2.84
          directory: ./deploy
          key: ${{secrets.SSH_PRIVATE_KEY}}

      - name: run deploy playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          inventory: |
            [do_servers]
            root@161.35.2.84
          directory: ./deploy
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --extra-vars "DB_PASSWORD=${{ secrets.DB_PASSWORD }} DB_USERNAME=${{ secrets.DB_USERNAME }} DB_HOST=${{ secrets.DB_HOST }} DB_PORT=${{ secrets.DB_PORT }} DB_NAME=${{ secrets.DB_NAME }} VERSION=${{ steps.commit.outputs.short }}"
